In [1]:
import sys

print(sys.executable)

c:\Users\sindh\OneDrive\Desktop\ecommerce-product-analytics\.venv\Scripts\python.exe

In [2]:
import pandas as pd

file_path = "../data/raw/Online Retail.xlsx"

df = pd.read_excel(file_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (541909, 8)

In [3]:
# Display the column names
print("Columns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

First 5 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
print("Data types:")
print(df.dtypes)

Data types:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [5]:
# Check missing values
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

print("\nMissing-value percentage:")
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage.round(2))

Missing values in each column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Missing-value percentage:
InvoiceNo       0.00
StockCode       0.00
Description     0.27
Quantity        0.00
InvoiceDate     0.00
UnitPrice       0.00
CustomerID     24.93
Country         0.00
dtype: float64

In [6]:
# Check duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)
print("Duplicate percentage:", round((duplicate_count / len(df)) * 100, 2), "%")

Number of duplicate rows: 5268
Duplicate percentage: 0.97 %

In [7]:
# Check cancelled invoices
cancelled_invoices = df["InvoiceNo"].astype(str).str.startswith("C")

print("Cancelled transaction rows:", cancelled_invoices.sum())
print("Cancellation percentage:", round(cancelled_invoices.mean() * 100, 2), "%")

Cancelled transaction rows: 9288
Cancellation percentage: 1.71 %

In [8]:
# Check negative quantities
negative_quantity = df["Quantity"] < 0

print("Rows with negative quantity:", negative_quantity.sum())
print(
    "Percentage with negative quantity:",
    round(negative_quantity.mean() * 100, 2),
    "%"
)

Rows with negative quantity: 10624
Percentage with negative quantity: 1.96 %

In [9]:
# Inspect duplicate rows
duplicates = df[df.duplicated(keep=False)]

display(duplicates.head(20))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom

In [10]:
# Inspect cancelled transactions
cancelled = df[df["InvoiceNo"].astype(str).str.startswith("C")]

display(cancelled.head(20))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [11]:
# Negative quantity records
negative_qty = df[df["Quantity"] < 0]

display(negative_qty.head(20))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom
1441,C536543,22632,HAND WARMER RED RETROSPOT,-1,2010-12-01 14:30:00,2.10,17841.0,United Kingdom
1442,C536543,22355,CHARLOTTE BAG SUKI DESIGN,-2,2010-12-01 14:30:00,0.85,17841.0,United Kingdom
1973,C536548,22244,3 HOOK HANGER MAGIC GARDEN,-4,2010-12-01 14:33:00,1.95,12472.0,Germany
1974,C536548,22242,5 HOOK HANGER MAGIC TOADSTOOL,-5,2010-12-01 14:33:00,1.65,12472.0,Germany
1975,C536548,20914,SET/5 RED RETROSPOT LID GLASS BOWLS,-1,2010-12-01 14:33:00,2.95,12472.0,Germany
1976,C536548,22892,SET OF SALT AND PEPPER TOADSTOOLS,-7,2010-12-01 14:33:00,1.25,12472.0,Germany
1977,C536548,22654,DELUXE SEWING KIT,-1,2010-12-01 14:33:00,5.95,12472.0,Germany
1978,C536548,22767,TRIPLE PHOTO FRAME CORNICE,-2,2010-12-01 14:33:00,9.95,12472.0,Germany
1979,C536548,22333,RETROSPOT PARTY BAG + STICKER SET,-1,2010-12-01 14:33:00,1.65,12472.0,Germany
1980,C536548,22245,"HOOK, 1 HANGER ,MAGIC GARDEN",-2,2010-12-01 14:33:00,0.85,12472.0,Germany

In [12]:
# Compare cancellation and negative-quantity records

print("Cancelled rows:", len(cancelled))
print("Negative quantity rows:", len(negative_qty))

print(
    "\nNegative quantity rows with cancellation invoice:",
    negative_qty["InvoiceNo"].astype(str).str.startswith("C").sum()
)

print(
    "Negative quantity rows without cancellation invoice:",
    (~negative_qty["InvoiceNo"].astype(str).str.startswith("C")).sum()
)

Cancelled rows: 9288
Negative quantity rows: 10624

Negative quantity rows with cancellation invoice: 9288
Negative quantity rows without cancellation invoice: 1336

In [13]:
# Inspect negative-quantity records that are NOT marked as cancellations

negative_non_cancel = df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
]

print("Rows:", len(negative_non_cancel))

display(
    negative_non_cancel[
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(30)
)

Rows: 1336

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7208,537016,21836,NaN,-15,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7209,537017,47556B,NaN,-69,2010-12-03 15:41:00,0.0,NaN,United Kingdom
7210,537018,84562A,NaN,-3,2010-12-03 15:42:00,0.0,NaN,United Kingdom
7211,537019,37474,NaN,-15,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7212,537020,21807,NaN,-30,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7213,537021,21011,NaN,-20,2010-12-03 15:43:00,0.0,NaN,United Kingdom
7291,537027,18098C,NaN,-140,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7292,537028,21696,NaN,-320,2010-12-03 16:36:00,0.0,NaN,United Kingdom
7293,537029,37476,NaN,-6,2010-12-03 16:37:00,0.0,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,NaN,United Kingdom

In [14]:
# Summarize the non-cancellation negative quantities

print("Unique invoice numbers:",
      negative_non_cancel["InvoiceNo"].nunique())

print("Unique stock codes:",
      negative_non_cancel["StockCode"].nunique())

print("\nQuantity statistics:")
print(negative_non_cancel["Quantity"].describe())

print("\nMost common descriptions:")
display(
    negative_non_cancel["Description"]
    .value_counts(dropna=False)
    .head(10)
)

Unique invoice numbers: 1336
Unique stock codes: 1082

Quantity statistics:
count    1336.000000
mean     -154.907934
std       588.292456
min     -9600.000000
25%       -84.000000
50%       -30.000000
75%        -8.000000
max        -1.000000
Name: Quantity, dtype: float64

Most common descriptions:

Description
NaN                       862
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
Name: count, dtype: int64

In [15]:
# Check zero and negative unit prices

zero_price = df["UnitPrice"] == 0
negative_price = df["UnitPrice"] < 0

print("Rows with zero UnitPrice:", zero_price.sum())
print("Rows with negative UnitPrice:", negative_price.sum())

print("\nZero-price transactions:")
display(
    df.loc[
        zero_price,
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(20)
)

print("\nNegative-price transactions:")
display(
    df.loc[
        negative_price,
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(20)
)

Rows with zero UnitPrice: 2515
Rows with negative UnitPrice: 2

Zero-price transactions:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom

Negative-price transactions:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [16]:
# Inspect transactions with missing descriptions

missing_description = df[df["Description"].isna()]

print("Rows with missing Description:", len(missing_description))

display(
    missing_description[
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"]
    ].head(20)
)

Rows with missing Description: 1454

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom

In [17]:
# Inspect negative-price transactions

negative_price_rows = df[df["UnitPrice"] < 0]

print("Negative-price rows:")
display(
    negative_price_rows[
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice",
         "CustomerID", "Country"]
    ]
)

Negative-price rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [18]:
# Understand zero-price transactions

zero_price_rows = df[df["UnitPrice"] == 0]

print("Zero-price rows:", len(zero_price_rows))

print("\nDescriptions associated with zero-price transactions:")
display(
    zero_price_rows["Description"]
    .value_counts(dropna=False)
    .head(20)
)

Zero-price rows: 2515

Descriptions associated with zero-price transactions:

Description
NaN                                1454
check                               159
?                                    47
damages                              45
damaged                              43
found                                25
sold as set on dotcom                20
adjustment                           16
Damaged                              14
FRENCH BLUE METAL DOOR SIGN 1         9
thrown away                           9
Unsaleable, destroyed.                9
amazon                                8
FRENCH BLUE METAL DOOR SIGN 8         8
Found                                 8
FRENCH BLUE METAL DOOR SIGN 4         7
FRENCH BLUE METAL DOOR SIGN No        7
OWL DOORSTOP                          7
FRENCH BLUE METAL DOOR SIGN 3         7
RECIPE BOX PANTRY YELLOW DESIGN       7
Name: count, dtype: int64

In [19]:
# Check whether zero-price transactions are cancellations or normal invoices

print(
    "Zero-price cancellation rows:",
    zero_price_rows["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

print(
    "Zero-price positive-quantity rows:",
    (zero_price_rows["Quantity"] > 0).sum()
)

print(
    "Zero-price negative-quantity rows:",
    (zero_price_rows["Quantity"] < 0).sum()
)

Zero-price cancellation rows: 0
Zero-price positive-quantity rows: 1179
Zero-price negative-quantity rows: 1336

In [20]:
# Define candidate valid sales

valid_sales_mask = (
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
)

candidate_sales = df[valid_sales_mask].copy()

print("Raw rows:", len(df))
print("Candidate valid sales rows:", len(candidate_sales))
print(
    "Rows excluded:",
    len(df) - len(candidate_sales)
)
print(
    "Percentage retained:",
    round(len(candidate_sales) / len(df) * 100, 2),
    "%"
)

Raw rows: 541909
Candidate valid sales rows: 530104
Rows excluded: 11805
Percentage retained: 97.82 %

In [21]:
print(
    "Candidate sales with missing Description:",
    candidate_sales["Description"].isna().sum()
)

print(
    "Candidate sales with missing CustomerID:",
    candidate_sales["CustomerID"].isna().sum()
)

print(
    "Candidate sales with zero UnitPrice:",
    (candidate_sales["UnitPrice"] == 0).sum()
)

print(
    "Candidate sales with negative Quantity:",
    (candidate_sales["Quantity"] < 0).sum()
)

Candidate sales with missing Description: 0
Candidate sales with missing CustomerID: 132220
Candidate sales with zero UnitPrice: 0
Candidate sales with negative Quantity: 0

In [22]:
print(
    "Duplicate rows within candidate sales:",
    candidate_sales.duplicated().sum()
)

Duplicate rows within candidate sales: 5226

In [23]:
# Inspect duplicate candidate sales

duplicate_sales = candidate_sales[
    candidate_sales.duplicated(keep=False)
].sort_values(
    by=["InvoiceNo", "StockCode", "Description", "Quantity"]
)

display(duplicate_sales.head(30))

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
548,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
597,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
569,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
611,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
603,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom

In [24]:
# Count duplicate groups

duplicate_group_count = (
    candidate_sales
    .groupby(
        ["InvoiceNo", "StockCode", "Description",
         "Quantity", "InvoiceDate", "UnitPrice", "CustomerID", "Country"],
        dropna=False
    )
    .size()
)

print("Total duplicate groups:", (duplicate_group_count > 1).sum())

print("\nLargest duplicate group sizes:")
print(
    duplicate_group_count[
        duplicate_group_count > 1
    ].sort_values(ascending=False).head(10)
)

Total duplicate groups: 4842

Largest duplicate group sizes:
InvoiceNo  StockCode  Description                          Quantity  InvoiceDate          UnitPrice  CustomerID  Country
555524     22698      PINK REGENCY TEACUP AND SAUCER       1         2011-06-05 11:37:00  2.95       16923.0     United Kingdom    20
           22697      GREEN REGENCY TEACUP AND SAUCER      1         2011-06-05 11:37:00  2.95       16923.0     United Kingdom    12
572861     22775      PURPLE DRAWERKNOB ACRYLIC EDWARDIAN  12        2011-10-26 12:46:00  1.25       14102.0     United Kingdom     8
538514     21756      BATH BUILDING BLOCK WORD             1         2010-12-12 14:27:00  5.95       15044.0     United Kingdom     6
541266     21755      LOVE BUILDING BLOCK WORD             1         2011-01-16 16:25:00  5.95       15673.0     United Kingdom     6
540524     21756      BATH BUILDING BLOCK WORD             1         2011-01-09 12:53:00  5.95       16735.0     United Kingdom     6
572344     M          Manual                               48        2011-10-24 10:43:00  1.50       14607.0     United Kingdom     6
541266     21754      HOME BUILDING BLOCK WORD             1         2011-01-16 16:25:00  5.95       15673.0     United Kingdom     6
578289     23395      BELLE JARDINIERE CUSHION COVER       1         2011-11-23 14:07:00  3.75       17841.0     United Kingdom     6
538517     22749      FELTCRAFT PRINCESS CHARLOTTE DOLL    1         2010-12-12 16:05:00  3.75       17618.0     United Kingdom     5
dtype: int64

In [25]:
# Remove exact duplicate transactions
clean_sales = candidate_sales.drop_duplicates().copy()

print("Rows before duplicate removal:", len(candidate_sales))
print("Rows after duplicate removal:", len(clean_sales))
print("Duplicate rows removed:", len(candidate_sales) - len(clean_sales))

Rows before duplicate removal: 530104
Rows after duplicate removal: 524878
Duplicate rows removed: 5226

In [26]:
# Verify duplicate removal

print("Remaining duplicate rows:", clean_sales.duplicated().sum())

Remaining duplicate rows: 0

In [27]:
# Calculate transaction revenue

clean_sales["Revenue"] = (
    clean_sales["Quantity"] * clean_sales["UnitPrice"]
)

print("Revenue column created.")
display(clean_sales.head())

Revenue column created.

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [28]:
print("Revenue statistics:")
print(clean_sales["Revenue"].describe())

print("\nTotal revenue:")
print(round(clean_sales["Revenue"].sum(), 2))

Revenue statistics:
count    524878.000000
mean         20.275399
std         271.693566
min           0.001000
25%           3.900000
50%           9.920000
75%          17.700000
max      168469.600000
Name: Revenue, dtype: float64

Total revenue:
10642110.8

In [29]:
# Save cleaned sales dataset

output_path = "../data/processed/clean_sales.csv"

clean_sales.to_csv(output_path, index=False)

print("Cleaned sales dataset saved successfully!")
print("File:", output_path)
print("Rows:", len(clean_sales))
print("Columns:", len(clean_sales.columns))

Cleaned sales dataset saved successfully!
File: ../data/processed/clean_sales.csv
Rows: 524878
Columns: 9

In [30]:
# Final quality check

print("Shape:", clean_sales.shape)

print("\nMissing values:")
print(clean_sales.isnull().sum())

print("\nDuplicate rows:")
print(clean_sales.duplicated().sum())

print("\nMinimum quantity:")
print(clean_sales["Quantity"].min())

print("\nMinimum unit price:")
print(clean_sales["UnitPrice"].min())

print("\nMinimum revenue:")
print(clean_sales["Revenue"].min())

Shape: (524878, 9)

Missing values:
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132186
Country             0
Revenue             0
dtype: int64

Duplicate rows:
0

Minimum quantity:
1

Minimum unit price:
0.001

Minimum revenue:
0.001

In [31]:
# Create a separate cancellation dataset

cancellations = df[
    df["InvoiceNo"].astype(str).str.startswith("C")
].copy()

cancellations["Revenue"] = (
    cancellations["Quantity"] * cancellations["UnitPrice"]
)

print("Cancellation rows:", len(cancellations))
print("Cancellation revenue/value:", round(cancellations["Revenue"].sum(), 2))

Cancellation rows: 9288
Cancellation revenue/value: -896812.49

In [32]:
# Create special/adjustment transactions dataset

special_transactions = df[
    (df["Quantity"] < 0) &
    (~df["InvoiceNo"].astype(str).str.startswith("C"))
].copy()

print("Special transaction rows:", len(special_transactions))

print("\nTop descriptions:")
display(
    special_transactions["Description"]
    .value_counts(dropna=False)
    .head(15)
)

Special transaction rows: 1336

Top descriptions:

Description
NaN                       862
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
damages?                    5
wet damaged                 5
ebay                        5
smashed                     4
missing                     3
Name: count, dtype: int64

In [33]:
# Save excluded transaction datasets

cancellations.to_csv(
    "../data/processed/cancellations.csv",
    index=False
)

special_transactions.to_csv(
    "../data/processed/special_transactions.csv",
    index=False
)

print("Saved:")
print("- cancellations.csv")
print("- special_transactions.csv")

Saved:
- cancellations.csv
- special_transactions.csv